import type { Metadata } from "next";
import "./globals.css";
import { Header } from "../../components/header/Header";
import { golos } from "./fonts";
import NextTopLoader from "nextjs-toploader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ru'>
    <body className={`${golos.variable} min-w-[320px]`}>
            <Header />
            <NextTopLoader
                color='#D7F943'
                shadow='0 2px 10px #FFD600, 0 0 5px #D7F943'
                initialPosition={0.5}
                showSpinner={false}
                speed={500}
            />
            <main>{children}</main>
    </body>
</html>
  );
}
